### ISSUE TITLE
Add new feed source UI problem

### ISSUE THREAD

**Issue by kpwebb** [conveyal/gtfs-data-manager#54]
Clicking the "Add new feed source" results in a non-obvious insert into the main feed list. The user never sees the new "unnamed source" in the list.

Let's change this so we get something obvious at the top of the list that can then be inserted on save.

Also need to resort the list on save

**Comment by mattwigway** [comment]
I believe the list is already resorted when you edit the name of a feed source. We just need to put new feed sources at the top of the list.

**Comment by mattwigway** [comment]
I didn't implement re-sort on save/edit name, because one could be editing a feed and it will move around in the list. But they are sorted if you navigate away and back.
