### ISSUE TITLE
Fails to require JS libraries

### ISSUE THREAD

**Issue by hannesj** [conveyal/gtfs-data-manager#65]
When opening the application after having installed according to the readme I get the following errors in the browser.

    Uncaught Error: failed to require "underscore" build.js:11
    Uncaught Error: failed to require "jquery"

**Comment by mattwigway** [comment]
Does the `component build` step succeed?

**Comment by tpievila** [comment]
I have the same problem, and in my case the `component build` first gave
```
       fatal : timeout of 5000ms exceeded for "https://codeload.github.co/kpwebb/select2/legacy.tar.gz/3.4.8"

    fs.js:769
        return binding.unlink(pathModule._makeLong(path));
                       ^
  Error: ENOENT, no such file or directory '/home/hukka/repos/gtfs-data-manager/public/components/moment/moment/2.9.0.tar.gz'
    at Object.fs.unlinkSync (fs.js:769:18)
    at process.onexit (/home/hukka/node_modules/component/node_modules/component-resolver/node_modules/component-downloader/build/archive.js:442:12)
    at process.emit (events.js:117:20)
    at process.exit (node.js:711:17)
    at Object.exports.fatal (/home/hukka/node_modules/component/node_modules/component-consoler/index.js:73:11)
    at Resolver.<anonymous> (/home/hukka/node_modules/component/bin/component-build:180:28)
    at Object._onImmediate (/home/hukka/node_modules/component/node_modules/co/index.js:52:14)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

but on second attempt continued and passed without errors.
When that error was given, public/components/moment/moment/tmp-qyuvulqh1d2yy14i.2.9.0.tar.gz did exist, but no 2.9.0.tar.gz.

**Comment by hannesj** [comment]
Hi @mattwigway,

Yes the build succeeds with 
```
gtfs-data-manager@natsumi:~/public$ component build

       build : resolved in 118ms
       build : build/build.css in 490ms - 154kb
       build : files in 555ms
       build : build/build.js in 565ms - 1038kb
```

If I replace the short names used in the require with the full names (e.g. ```jashkenas~underscore@1.7.0```) it works properly.

**Comment by hannesj** [comment]
component.modules is the following http://pastebin.com/je6E97zy

**Comment by mattwigway** [comment]
Hmm. What version of component are you using?
		
		
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Wed, 11 Feb 2015 04:15:53 -0500  notifications@github.com  wrote ----component.modules is the following http://pastebin.com/je6E97zy

**Comment by tpievila** [comment]
> 		Hmm. What version of component are you using?

1.0.2

-- 
Tomi Pievil�inen, +358 400 487 504
A: Because it disrupts the natural way of thinking.
Q: Why is top posting frowned upon?

**Comment by mattwigway** [comment]
Hmm. I haven't tested with that new of a version. I wonder if that's it.Are you building with -d and -c? I've had trouble with that in the past.
		
		
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Wed, 11 Feb 2015 06:15:17 -0500  notifications@github.com  wrote ----> 		Hmm. What version of component are you using?

1.0.2

-- 
Tomi Pievil inen, +358 400 487 504
A: Because it disrupts the natural way of thinking.
Q: Why is top posting frowned upon?

**Comment by hannesj** [comment]
Ok, running component build -c -d seems to do the trick. I think it is with the -d, as it creates the short aliases for the libraries used.

**Comment by mattwigway** [comment]
Good to know, thanks for taking this down.
		
		
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Wed, 11 Feb 2015 07:01:16 -0500  notifications@github.com  wrote ----Ok, running component build -c -d seems to do the trick. I think it is with the -d, as it creates the short aliases for the libraries used.
