### ISSUE TITLE
Dependency error on Play 2.3.5 

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-data-manager#87]
I'm running into a dependency issue when play 2.3.5 plugin sbt plugin is specified.  On startup, the `sbt-run-support-210#sbt-run-support-210_2.10;0.1-SNAPSHOT ` is missing/will not load.  (Issue is similar to what is documented here: http://grokbase.com/p/gg/play-framework/14ac5646wz/play-2-3-5-released).

When changing the version to `2.3.4` in `plugins.sbt`, the application starts up successfully.

**Comment by mattwigway** [comment]
@demory fixed this by bumping play to 2.3.9.
